---
title: "Chalet Machine Learning 2018"
author: "Stéphane Caron et Samuel Perreault"
date: '2018-08-24'
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

## Contenu

1. Mise en contexte
2. Qu'est qu'une communauté?
3. Les objectifs recherchés
4. Comment faire vivre la communauté?
5. Discussions ouvertes

---

## Chalet Machine Learning 2017

**Résumé:**

- Plus petit groupe (4 personnes)
- Travailler sur une problématique de machine learning
- Avoir du fun !

---

## Prémisse de base

Utiliser les forces et les intérêts d'un groupe de personnes afin de créer du momemtum, du savoir et de l'engouement autour d'une thématique commune qui tourne autour du machine learning, des statistiques et du data science.

---

## Le concept de communauté

Une communauté représente ...

- En biologie: un système au sein duquel des organismes vivants **partagent** un environnement commun.
- En sociologie: un regroupement de personnes autour d'une **thématique commune**.
- En droit: un groupe de personnes possédant et jouissant de façon **indivise** d'un patrimoine commun.

---

## Communauté machine learning

Dans ce contexte, la communauté représente un groupe de personnes ayant tous des **intérêts communs** pour cette thématique et qui **partagent** leurs connaissances et leurs idées dans le but de créer quelque chose de **collectivement** plus grand.

---

## Communauté vs équipe

La différence entre ce concept et un équipe de projet réside entres autres dans la **durée de la communauté qui est indeterminée**. De plus, il n'y pas de responsabilités requises pour faire partie de ce genre de groupe. Autrement dit, chaque personne décide comment, quand et en quoi elle contribuera. 

Au final, peu importe la contribution, chaque membre a quelque chose à retirer individuellement de cet effort collectif.

---

## Les objectifs recherchés

- Faciliter le lien entre un groupe de personnes partageant les mêmes intérêts.
- Créer une plateforme permettant de contribuer à plusieurs projets.
- Utiliser l'effet de groupe comme source de motivation individuelle.
- Mettre de l'avant le partage de connaissances à l'intérieur du groupe.
- Donner plus de visibilité et de reconnaissance à notre champ d'intérêt.
- Avoir une *gang* à nos côtés pour avoir davantage de plaisir dans nos projets.

---
class: center, middle

## Comment faire vivre la communauté?

---

## Le blog

L'objectif du blog est d'avoir un médium pour lequel on peut facilement communiquer et partager nos intérêts.

- Facile d'utilisation
- Moyen efficace de partager des idées/découvertes/intrêts
- Donner de la visibilité

---

## Les projets

Utiliser l'effet de groupe comme source de motivation pour des projets collaboratifs.

> "Talk to strangers!"
>
> `-` Phil Cook, Eaux Claires 2018

Nos idées sont souvent meilleures qu'on le pense ...

---

## Les projets

La communauté est présente pour **faciliter** la réalisation de projets personnels.

- Présence de personnes ressources pour contribuer aux divers projets.
- Plateforme simple et efficace pour partager des difficultés.
- Opportunités accrues de projets en profitant d'un réseau de contact partagé.
- Profiter de la créativité de tous afin de générer encore plus d'idées.

---

## Les évènements

L'objectif des évènements est de créer un effet de rassemblement, de famille ainsi que de se donner des occasions de partager certaines choses en personnes.

- Faciliter les relations humaines entres les gens de la communauté.
- Obtenir des opportunités de présenter du contenu en personnes.
- Discuter et *brainstormer* sur des projets ou des sujets concernant la communauté.
- Avoir du plaisir !!

---
class: center, middle

## Tour de table

---
class: center, middle

## Discussions ouvertes

---
class: center, middle

## Quels sont les sujets d'articles et de projets travaillés par les membres de la communauté?

---
class: center, middle

## Quelle langue est utilisée pour le site web et pour les articles?

---
class: center, middle

## Est-ce qu'on se fixe un système de *peer review* et de contrôle de qualité pour la publication d'articles?

---
class: center, middle

## De quelle façon pourrait-on donner de la visibilité à la communauté?

---
class: center, middle

## Quel nom pourrait-on donner à la communauté?



